### ISSUE TITLE
Long-term archiver

### ISSUE THREAD

**Issue by dabail10** [CESM-Development/cime#230]
I am getting the following message when I try to manually submit the long-term archiver in cesm1_5_alpha01.

Can't locate SetupTools.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . ./Tools) at ./g.e15.GIAF.T62_g16.001.lt_archive line 11.

Do we have a workaround?

**Comment by jedwards4b** [comment]
add to the top of case.ltarchive:

my $cimeroot = `xmlquery CIMEROOT -value`
my $perl5lib = "$cimeroot/utils/perl5lib";
push(@INC,$perl5lib);

I'll put a fix in my next cime tag.

On Wed, Oct 14, 2015 at 10:13 AM, dabail10 notifications@github.com wrote:

> I am getting the following message when I try to manually submit the
> long-term archiver in cesm1_5_alpha01.
> 
> Can't locate SetupTools.pm in @INC https://github.com/INC (@INC
> https://github.com/INC contains: /usr/local/lib64/perl5
> /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl
> /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . ./Tools)
> at ./g.e15.GIAF.T62_g16.001.lt_archive line 11.
> 
> Do we have a workaround?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/230.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by dabail10** [comment]
This does not work. Also, I copied SetupTool.pm over to my local tools and
now it cannot find Run/RunChecks.pm.

Dave

On Wed, Oct 14, 2015 at 11:31 AM, jedwards4b notifications@github.com
wrote:

> add to the top of case.ltarchive:
> 
> my $cimeroot = `xmlquery CIMEROOT -value`
> my $perl5lib = "$cimeroot/utils/perl5lib";
> push(@INC,$perl5lib);
> 
> I'll put a fix in my next cime tag.
> 
> On Wed, Oct 14, 2015 at 10:13 AM, dabail10 notifications@github.com
> wrote:
> 
> > I am getting the following message when I try to manually submit the
> > long-term archiver in cesm1_5_alpha01.
> > 
> > Can't locate SetupTools.pm in @INC https://github.com/INC (@INC
> > https://github.com/INC contains: /usr/local/lib64/perl5
> > /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl
> > /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . ./Tools)
> > at ./g.e15.GIAF.T62_g16.001.lt_archive line 11.
> > 
> > Do we have a workaround?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CESM-Development/cime/issues/230.
> 
> ## 
> 
> Jim Edwards
> 
> CESM Software Engineer
> National Center for Atmospheric Research
> Boulder, CO
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/230#issuecomment-148127125
> .

## 

David A Bailey
 email: dbailey_at_ucar.edu
National Center for Atmospheric Research   phone: 303-497-1737
PO Box 3000
fax  : 303-497-1700
Boulder, CO 80307-3000
                   http://www.cgd.ucar.edu/staff/dbailey

**Comment by jedwards4b** [comment]
You're correct.   I've turned this over to Jay, it won't be in my tag.

**Comment by dabail10** [comment]
We have the fix:

my $cimeroot = `./xmlquery CIMEROOT -value`;
print "$cimeroot \n";
my $perl5lib = "$cimeroot/utils/perl5lib";
my $configdir = "$perl5lib/Config";
push(@INC, $perl5lib, $configdir);

my $toolsdir = "./Tools";
push(@INC, $toolsdir);
require SetupTools;
require Run::RunChecks;
require Module::ModuleLoader;

Dave

On Wed, Oct 14, 2015 at 2:03 PM, jedwards4b notifications@github.com
wrote:

> You're correct. I've turned this over to Jay, it won't be in my tag.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/230#issuecomment-148179761
> .

## 

David A Bailey
 email: dbailey_at_ucar.edu
National Center for Atmospheric Research   phone: 303-497-1737
PO Box 3000
fax  : 303-497-1700
Boulder, CO 80307-3000
                   http://www.cgd.ucar.edu/staff/dbailey

**Comment by sholly** [comment]
Just as an update, Danica was having similar issues with the lt_archive job script.  This was mostly due to the fact that she was using a CLM tag that did not have any of the lt_archive updates.  The lt_archive run script should be working, but we should leave this open until we have a proper test for this functionality.

**Comment by dabail10** [comment]
Mine is still not working even with all of the perl statements. When I try
to submit it as:

bsub < $case.lt_archive

It rejects it because it cannot find a wallclock time. However, it is right
there at the top of the script. I think I am missing something about how
the submit script works now.

Dave

On Tue, Oct 20, 2015 at 9:14 AM, Jay Shollenberger <notifications@github.com

> wrote:
> 
> Just as an update, Danica was having similar issues with the lt_archive
> job script. This was mostly due to the fact that she was using a CLM tag
> that did not have any of the lt_archive updates. The lt_archive run script
> should be working, but we should leave this open until we have a proper
> test for this functionality.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/230#issuecomment-149597544
> .

## 

David A Bailey
 email: dbailey_at_ucar.edu
National Center for Atmospheric Research   phone: 303-497-1737
PO Box 3000
fax  : 303-497-1700
Boulder, CO 80307-3000
                   http://www.cgd.ucar.edu/staff/dbailey

**Comment by bertinia** [comment]
I've gathered some requirements from Rory Kelly, Jim, Jay, and Gary on what needs
to go into a rewrite of the lt_archive.sh into perl. I will start working on it this week.
